# Generated by Django 4.2.3 on 2023-08-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0005_ticket_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='treated',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
